### ISSUE TITLE
Error using download function

### ISSUE THREAD

**Issue by EmanuelCastanho** [nsidc/earthaccess#252]
Hi,

When using the download function:

`files = earthaccess.download(results, "downloads")`

 I get the following error:

```
Granules found: 2
Traceback (most recent call last):
  File "/Users/USER/Desktop/fast_code_testing/fast_code_testing.py", line 30, in <module>
    files = earthaccess.download(results, "./local_folder")
  File "/Users/USER/miniconda3/envs/fast_code_testing-env/lib/python3.9/site-packages/earthaccess/api.py", line 167, in download
    results = earthaccess.__store__.get(granules, local_path, provider, threads)
AttributeError: 'NoneType' object has no attribute 'get'
```

This is my code:
```
results = earthaccess.search_data(
    short_name='VNP09_NRT',
    version="1",
    cloud_hosted=True,
    bounding_box=(-31.59668, 36.677231, -24.631348, 39.993956),
    temporal=("2023-06-22", "2023-06-23"),
    count=-1
)
```
and this was the solution I found:
```
data_urls = [granule.data_links(access="external") for granule in results]
for url in data_urls:
    product_name = url[0].split('/')[-1]
    product_path = os.path.join("downloads", product_name)
    r = requests.get(url[0], allow_redirects=True)
    with open(product_path, "wb") as f:
        f.write(r.content)
```

Also, note that `version="1"`, if `version="001"` it returns 0 granules found.

Thanks!

**Comment by betolink** [comment]
Hi @EmanuelCastanho, I think the error is because the authentication with EDL failed. I'll work on adding more explicit error messages... I tried this and it worked:

```python
import earthaccess

# using my credentials
earthaccess.login()

# this returned 2 files 
results = earthaccess.search_data(
    short_name='VNP09_NRT',
    cloud_hosted=True,
    bounding_box=(-31.59668, 36.677231, -24.631348, 39.993956),
    temporal=("2023-06-22", "2023-06-23"),
)

# downloaded 2 HDF4 files each ~280 MB
files = earthaccess.download(results, "downloads")
```

**Comment by EmanuelCastanho** [comment]
Yes, I tried and it is working fine. Thank you!
