### ISSUE TITLE
Error Downloading TROPOMI Ozone Data

### ISSUE THREAD

**Issue by zfasnacht1013** [nsidc/earthaccess#758]
Getting the following error when trying to download TROPOMI ozone data

```
>>> earthaccess.download(results,file_path)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/explore/nobackup/people/zfasnach/miniconda3/envs/gpu/lib/python3.11/site-packages/earthaccess/api.py", line 188, in download
    results = earthaccess.__store__.get(granules, local_path, provider, threads)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/explore/nobackup/people/zfasnach/miniconda3/envs/gpu/lib/python3.11/site-packages/earthaccess/store.py", line 475, in get
    files = self._get(granules, local_path, provider, threads)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/explore/nobackup/people/zfasnach/miniconda3/envs/gpu/lib/python3.11/site-packages/multimethod/__init__.py", line 367, in __call__
    func = self.dispatch(*args)
           ^^^^^^^^^^^^^^^^^^^^
  File "/explore/nobackup/people/zfasnach/miniconda3/envs/gpu/lib/python3.11/site-packages/multimethod/__init__.py", line 362, in dispatch
    return self.select(types, matches)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/explore/nobackup/people/zfasnach/miniconda3/envs/gpu/lib/python3.11/site-packages/multimethod/__init__.py", line 346, in select
    raise DispatchError(f"{self.__name__}: {len(keys)} methods found", types, keys)
multimethod.DispatchError: ('_get: 0 methods found', (<class 'earthaccess.store.Store'>, <class 'list'>, <class 'pathlib.PosixPath'>, <class 'NoneType'>, <class 'int'>), set())
```

The code is...
```
>>> import earthaccess
>>> earthaccess.login(persist=True)
<earthaccess.auth.Auth object at 0x7f42a9be15d0>
>>> start_date='2024-03-21 00:00:00'
>>> end_date='2024-03-21 23:59:59'
>>> results = earthaccess.search_data(short_name = 'S5P_L2__O3_TOT_HiR',cloud_hosted=True,temporal=(start_date,end_date),count=20,bounding_box=(-180,-90,180,90))
Granules found: 15
>>> file_path = '/explore/nobackup/people/zfasnach/PACE_Data/'
>>> results = earthaccess.open(results)
Opening 15 granules, approx size: 4.68 GB
QUEUEING TASKS | : 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 5193.11it/s]
PROCESSING TASKS | : 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:02<00:00,  5.92it/s]
COLLECTING RESULTS | : 100%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 15/15 [00:00<00:00, 271183.45it/s]
>>> earthaccess.download(results,file_path)
```

Any idea the cause of this?

**Comment by zfasnacht1013** [comment]
Sorry found my bug so closing...

\close
