### ISSUE TITLE
[BUG] `build-docs.sh` is failing to build local docs

### ISSUE THREAD

**Issue by andypbarrett** [nsidc/earthaccess#802]
### Is this issue already tracked somewhere, or is this a new report?

- [X] I've reviewed existing issues and couldn't find a duplicate for this problem.

### Current Behavior

In trying to build docs locally with `./scripts/build-docs.sh` I get a `ModuleNotFoundError: No module named 'mkdocs.tests'`.

This may be related to https://github.com/mkdocs/mkdocs/issues/3702

### Expected Behavior

I expect `build-docs.sh` to generate html locally for the docs

### Steps To Reproduce

I'm using the `earthaccess-dev` environment that I just ran `mamba env update -f ci/environment-dev.yml`

The current mkdocs associated versions are:
```
$ mamba list | grep mkdocs
mkdocs                    1.6.1              pyhd8ed1ab_0    conda-forge
mkdocs-autorefs           1.2.0              pyhd8ed1ab_1    conda-forge
mkdocs-get-deps           0.2.0              pyhd8ed1ab_0    conda-forge
mkdocs-jupyter            0.22.0             pyhd8ed1ab_0    conda-forge
mkdocs-material           8.5.11             pyhd8ed1ab_0    conda-forge
mkdocs-material-extensions 1.3.1              pyhd8ed1ab_0    conda-forge
mkdocs-redirects          1.2.1              pyhd8ed1ab_0    conda-forge
mkdocstrings              0.26.0             pyhd8ed1ab_0    conda-forge
mkdocstrings-python       1.10.9             pyhd8ed1ab_0    conda-forge
```
Running `$ ./scripts/build-docs.sh`  

I get the following Traceback
```
Traceback (most recent call last):
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/site-packages/mkdocs/__main__.py", line 370, in <module>
    cli()
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/site-packages/click/core.py", line 1157, in __call__
    return self.main(*args, **kwargs)
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/site-packages/click/core.py", line 1078, in main
    rv = self.invoke(ctx)
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/site-packages/click/core.py", line 1688, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/site-packages/click/core.py", line 1434, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/site-packages/click/core.py", line 783, in invoke
    return __callback(*args, **kwargs)
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/site-packages/mkdocs/__main__.py", line 285, in build_command
    cfg = config.load_config(**kwargs)
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/site-packages/mkdocs/config/base.py", line 374, in load_config
    errors, warnings = cfg.validate()
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/site-packages/mkdocs/config/base.py", line 231, in validate
    run_failed, run_warnings = self._validate()
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/site-packages/mkdocs/config/base.py", line 188, in _validate
    self[key] = config_option.validate(value)
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 186, in validate
    return self.run_validation(value)
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 1065, in run_validation
    self.load_plugin_with_namespace(name, cfg)
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 1103, in load_plugin_with_namespace
    return (name, self.load_plugin(name, config))
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/site-packages/mkdocs/config/config_options.py", line 1121, in load_plugin
    plugin_cls = self.installed_plugins[name].load()
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/apbarret/mambaforge/envs/earthaccess-dev/lib/python3.10/site-packages/mkdocs_jupyter/plugin.py", line 10, in <module>
    from mkdocs.tests.base import get_markdown_toc
ModuleNotFoundError: No module named 'mkdocs.tests'
```

### Environment

```markdown
- OS: Ubuntu 22.04.4 LTS
- Python: Python 3.10.14
```

**Comment by chuckwondo** [comment]
Try bumping mkdocs-jupyter to version 0.24.8, which I believe should get past this problem.

**Comment by andypbarrett** [comment]
I think my issue was that I only updated my environment with `ci/environment-dev.yml` and did not do the `poetry install` step.  I thought that only applied to setting up the environment.  This may be moot once @MattF-NSIDC tears out Poetry.

**Comment by andypbarrett** [comment]
I'll close this for now.
